/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import com.mysql.cj.jdbc.Blob;
import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.nio.file.Files;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import java.sql.PreparedStatement;
/**
 *
 * @author GALUH DIVITA
 */
public class Project1 extends javax.swing.JFrame {
    private DefaultTableModel DftTbldata_mahasiswa;
    private String SQL; 
    private PreparedStatement stat;
    private ResultSet rs;
    private String filename;
    private Blob foto;

    public void setFoto(Blob foto) {
        this.foto = foto;
    }
    /**
     * Creates new form Project1
     */
    public Project1() {
        initComponents();
        TampilData();
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false);
    }

    public void Clean(){
        
        txt_nim.setText("");
        txt_nama.setText("");
        txt_kelas.setText("");
        txt_dosenpembimbing.setText("");
        txt_tempat_tanggal.setText ("");
        box_agama.setSelectedIndex(0);
        box_jeniskelamin.setSelectedIndex(0);
        txt_alamat.setText(""); 
        txt_notelp.setText(""); 
        lbl_photo.setText("");
        String path;
    }
    
    private void cariData(String key){


DftTbldata_mahasiswa = new DefaultTableModel();
        DftTbldata_mahasiswa.addColumn("NIM");
        DftTbldata_mahasiswa.addColumn("Nama");
        DftTbldata_mahasiswa.addColumn("Kelas");
        

        tbdata.setModel(DftTbldata_mahasiswa);
        Connection conn = Koneksi.getConnection();
        
        try {
            java.sql.Statement stmt = conn.createStatement();
            SQL = "SELECT * FROM tb_gdata1 WHERE nama LIKE '%"+key+"%' OR nim LIKE '%"+key+"%' OR kelas LIKE '%"+key+"%'";
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            while (res.next()) {
                DftTbldata_mahasiswa.addRow(new Object[]{
                    res.getString("nim"),
                    res.getString("nama"),
                    res.getString("kelas"),
                });
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
    
    
    public final void TampilData() {
        DftTbldata_mahasiswa = new DefaultTableModel();
        DftTbldata_mahasiswa.addColumn("NIM");
        DftTbldata_mahasiswa.addColumn("Nama");
        DftTbldata_mahasiswa.addColumn("Kelas");
       

        tbdata.setModel(DftTbldata_mahasiswa);
        Connection conn = Koneksi.getConnection();
        
        try {
            java.sql.Statement stmt = conn.createStatement();
            SQL = "SELECT * FROM tb_gdata1";
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            while (res.next()) {
                DftTbldata_mahasiswa.addRow(new Object[]{
                    res.getString("nim"),
                    res.getString("nama"),
                    res.getString("kelas"),
                    res.getString("dosen_pembimbing"),
                    res.getString("tempat_tanggal"),
                    res.getString("agama"),
                    res.getString("jenis_kelamin"),
                    res.getString("alamat"),
                    res.getString("notelp"),
                    res.getString("foto"),
                });
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jb = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        bg_awal = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        btn_panAbout = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_panForm = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_panALL = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_exit = new javax.swing.JPanel();
        tx_exit = new javax.swing.JLabel();
        ic_exit = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        panel_border = new keeptoo.KGradientPanel();
        label_user = new javax.swing.JLabel();
        lbl_border = new javax.swing.JLabel();
        panel_utama = new javax.swing.JPanel();
        panel_show = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        box_agama = new javax.swing.JComboBox<>();
        btn_submit = new javax.swing.JPanel();
        tx_simpan = new javax.swing.JLabel();
        txt_kelas = new javax.swing.JTextField();
        txt_dosenpembimbing = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        btn_submit2 = new javax.swing.JPanel();
        tx_perbarui = new javax.swing.JLabel();
        txt_nim = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        txt_tempat_tanggal = new javax.swing.JTextField();
        box_jeniskelamin = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        txt_notelp = new javax.swing.JTextField();
        txt_alamat = new javax.swing.JTextField();
        lbl_photo = new javax.swing.JLabel();
        btn_foto = new javax.swing.JButton();
        panel_about = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        panel_input = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbdata = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        tx_cari = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        btn_dlt = new javax.swing.JPanel();
        tx_hapus = new javax.swing.JLabel();
        btn_view = new javax.swing.JPanel();
        tx_lihat = new javax.swing.JLabel();

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        bg_awal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 0, 102));
        kGradientPanel1.setkStartColor(new java.awt.Color(102, 153, 255));
        kGradientPanel1.setkTransparentControls(false);
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_panAbout.setBackground(new java.awt.Color(0, 0, 102));
        btn_panAbout.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_panAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_panAboutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_panAboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_panAboutMouseExited(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/icons8_about_16px.png"))); // NOI18N
        jLabel2.setToolTipText("");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel3.setBackground(new java.awt.Color(0, 0, 102));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("About Aplication");
        jLabel3.setToolTipText("");

        javax.swing.GroupLayout btn_panAboutLayout = new javax.swing.GroupLayout(btn_panAbout);
        btn_panAbout.setLayout(btn_panAboutLayout);
        btn_panAboutLayout.setHorizontalGroup(
            btn_panAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_panAboutLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        btn_panAboutLayout.setVerticalGroup(
            btn_panAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_panAboutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        kGradientPanel1.add(btn_panAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 260, 50));

        btn_panForm.setBackground(new java.awt.Color(0, 51, 153));
        btn_panForm.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_panForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_panFormMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_panFormMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_panFormMouseExited(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/icons8_add_25px.png"))); // NOI18N
        jLabel4.setToolTipText("");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel5.setBackground(new java.awt.Color(0, 51, 153));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Data Mahasiswa");
        jLabel5.setToolTipText("");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout btn_panFormLayout = new javax.swing.GroupLayout(btn_panForm);
        btn_panForm.setLayout(btn_panFormLayout);
        btn_panFormLayout.setHorizontalGroup(
            btn_panFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_panFormLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        btn_panFormLayout.setVerticalGroup(
            btn_panFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_panFormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        kGradientPanel1.add(btn_panForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 260, 50));

        btn_panALL.setBackground(new java.awt.Color(0, 0, 153));
        btn_panALL.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_panALL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_panALLMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_panALLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_panALLMouseExited(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/icons8_account_16px.png"))); // NOI18N
        jLabel6.setToolTipText("");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel7.setBackground(new java.awt.Color(0, 51, 153));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Data Semua Mahasiswa");
        jLabel7.setToolTipText("");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout btn_panALLLayout = new javax.swing.GroupLayout(btn_panALL);
        btn_panALL.setLayout(btn_panALLLayout);
        btn_panALLLayout.setHorizontalGroup(
            btn_panALLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_panALLLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        btn_panALLLayout.setVerticalGroup(
            btn_panALLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_panALLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        kGradientPanel1.add(btn_panALL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 260, 50));

        btn_exit.setBackground(new java.awt.Color(255, 255, 255));
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_exitMouseExited(evt);
            }
        });

        tx_exit.setBackground(new java.awt.Color(255, 255, 255));
        tx_exit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tx_exit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tx_exit.setText("EXIT");

        ic_exit.setBackground(new java.awt.Color(255, 255, 255));
        ic_exit.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        ic_exit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ic_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/icons8_outdent_24px_1.png"))); // NOI18N

        javax.swing.GroupLayout btn_exitLayout = new javax.swing.GroupLayout(btn_exit);
        btn_exit.setLayout(btn_exitLayout);
        btn_exitLayout.setHorizontalGroup(
            btn_exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_exitLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(ic_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tx_exit)
                .addContainerGap(176, Short.MAX_VALUE))
        );
        btn_exitLayout.setVerticalGroup(
            btn_exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_exitLayout.createSequentialGroup()
                .addGroup(btn_exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ic_exit, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(tx_exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        kGradientPanel1.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 260, 30));

        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 20));
        jSeparator1.setRequestFocusEnabled(false);
        kGradientPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 220, 30));

        jLabel10.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("GData");
        kGradientPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 220, 40));

        jSeparator2.setPreferredSize(new java.awt.Dimension(50, 20));
        jSeparator2.setRequestFocusEnabled(false);
        kGradientPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 180, 20));

        jLabel13.setBackground(new java.awt.Color(0, 0, 102));
        jLabel13.setFont(new java.awt.Font("News701 BT", 1, 8)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(196, 193, 193));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("© Gdata 2023");
        jLabel13.setToolTipText("");
        kGradientPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, 190, 30));

        bg_awal.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 560));

        panel_border.setkEndColor(new java.awt.Color(51, 0, 102));
        panel_border.setkGradientFocus(700);
        panel_border.setkStartColor(new java.awt.Color(102, 102, 255));
        panel_border.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_user.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_user.setForeground(new java.awt.Color(255, 255, 255));
        label_user.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_user.setText("Hello, wellcome  ");
        panel_border.add(label_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 247, 30));

        lbl_border.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbl_border.setForeground(new java.awt.Color(255, 255, 255));
        lbl_border.setText("Data Mahasiswa");
        lbl_border.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                lbl_borderComponentShown(evt);
            }
        });
        panel_border.add(lbl_border, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 440, 45));

        bg_awal.add(panel_border, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 870, 130));

        panel_utama.setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));
        jPanel1.setForeground(new java.awt.Color(51, 51, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel39.setBackground(new java.awt.Color(255, 255, 255));
        jLabel39.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("NIM");

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel31.setText("Kelas");

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel37.setText("Jenis Kelamin");

        box_agama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Disini >", "Islam", "Kristen", "Budha", "Hindu", "Konghucu" }));
        box_agama.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        box_agama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_agamaActionPerformed(evt);
            }
        });

        btn_submit.setBackground(new java.awt.Color(0, 51, 255));
        btn_submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_submitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_submitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_submitMouseExited(evt);
            }
        });

        tx_simpan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tx_simpan.setForeground(new java.awt.Color(255, 255, 255));
        tx_simpan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tx_simpan.setText("Simpan");
        tx_simpan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tx_simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tx_simpanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btn_submitLayout = new javax.swing.GroupLayout(btn_submit);
        btn_submit.setLayout(btn_submitLayout);
        btn_submitLayout.setHorizontalGroup(
            btn_submitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_submitLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(tx_simpan)
                .addGap(38, 38, 38))
        );
        btn_submitLayout.setVerticalGroup(
            btn_submitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tx_simpan, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        txt_kelas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_kelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kelasActionPerformed(evt);
            }
        });

        txt_dosenpembimbing.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_dosenpembimbing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dosenpembimbingActionPerformed(evt);
            }
        });

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel41.setText("Dosen Pembimbing");

        jLabel42.setFont(new java.awt.Font("Traditional Arabic", 0, 14)); // NOI18N
        jLabel42.setText("Agama");

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel43.setText("Alamat");

        btn_submit2.setBackground(new java.awt.Color(0, 51, 255));
        btn_submit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_submit2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_submit2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_submit2MouseExited(evt);
            }
        });

        tx_perbarui.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tx_perbarui.setForeground(new java.awt.Color(255, 255, 255));
        tx_perbarui.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tx_perbarui.setText("Perbarui");
        tx_perbarui.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout btn_submit2Layout = new javax.swing.GroupLayout(btn_submit2);
        btn_submit2.setLayout(btn_submit2Layout);
        btn_submit2Layout.setHorizontalGroup(
            btn_submit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_submit2Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(tx_perbarui, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        btn_submit2Layout.setVerticalGroup(
            btn_submit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tx_perbarui, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        txt_nim.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_nim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nimActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Nama");

        txt_nama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaActionPerformed(evt);
            }
        });

        jLabel44.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel44.setText("Tempat, Tanggal Lahir");

        txt_tempat_tanggal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_tempat_tanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tempat_tanggalActionPerformed(evt);
            }
        });

        box_jeniskelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Disini >", "Laki-laki", "Perempuan" }));
        box_jeniskelamin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        box_jeniskelamin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_jeniskelaminActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("No Telepon");

        txt_notelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_notelpActionPerformed(evt);
            }
        });

        txt_alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_alamatActionPerformed(evt);
            }
        });

        lbl_photo.setText("            Ukuran 4x6cm");
        lbl_photo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lbl_photo.setName(""); // NOI18N
        lbl_photo.setPreferredSize(new java.awt.Dimension(134, 172));
        lbl_photo.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                lbl_photoComponentAdded(evt);
            }
        });

        btn_foto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_foto.setLabel("Uploud");
        btn_foto.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btn_fotoStateChanged(evt);
            }
        });
        btn_foto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(115, 115, 115)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_nama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                            .addComponent(txt_nim, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_kelas, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_dosenpembimbing, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(btn_submit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                                .addComponent(btn_submit2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel20))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42)))
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_tempat_tanggal)
                                    .addComponent(box_jeniskelamin, 0, 269, Short.MAX_VALUE)
                                    .addComponent(txt_notelp, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(box_agama, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_alamat))))))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(btn_foto)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                        .addComponent(lbl_photo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txt_nim, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(txt_kelas, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_dosenpembimbing, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel41))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel44)
                            .addComponent(txt_tempat_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel42)
                            .addComponent(box_agama, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel37)
                            .addComponent(box_jeniskelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel43)
                            .addComponent(txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(txt_notelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_submit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_submit2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(lbl_photo, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_foto)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout panel_showLayout = new javax.swing.GroupLayout(panel_show);
        panel_show.setLayout(panel_showLayout);
        panel_showLayout.setHorizontalGroup(
            panel_showLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_showLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_showLayout.setVerticalGroup(
            panel_showLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_showLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panel_utama.add(panel_show, "card3");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("ABOUT APLICATION");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/icons8_id_male_student_100px.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("selain itu aplikasi ini berbasis desktop dengan tujuan memberikan penampilan GUI keren "); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Aplikasi ini dikembangkan dan dapat dijalankan di operasi Windows,"); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("serta memberikan kemudahan user untuk mengakses aplikasi ini. "); // NOI18N

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Aplikasi My GData"); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("Version 1.0.1 V"); // NOI18N

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Develop By GData TEAMS"); // NOI18N

        javax.swing.GroupLayout panel_aboutLayout = new javax.swing.GroupLayout(panel_about);
        panel_about.setLayout(panel_aboutLayout);
        panel_aboutLayout.setHorizontalGroup(
            panel_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_aboutLayout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addGroup(panel_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_aboutLayout.createSequentialGroup()
                        .addGroup(panel_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(502, Short.MAX_VALUE))
                    .addGroup(panel_aboutLayout.createSequentialGroup()
                        .addGroup(panel_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addGap(108, 108, 108))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_aboutLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );
        panel_aboutLayout.setVerticalGroup(
            panel_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_aboutLayout.createSequentialGroup()
                .addGroup(panel_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_aboutLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_aboutLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addGap(23, 23, 23)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        panel_utama.add(panel_about, "card4");

        jScrollPane2.setBorder(null);

        tbdata.setAutoCreateRowSorter(true);
        tbdata.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tbdata.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbdata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NIM", "Nama", "Kelas", "Dosen Pembimbing", "Tanggal Lahir", "Agama", "Jenis Kelamin", "Alamat"
            }
        ));
        tbdata.setGridColor(new java.awt.Color(255, 255, 255));
        tbdata.setIntercellSpacing(new java.awt.Dimension(5, 5));
        tbdata.setRowHeight(25);
        tbdata.setSelectionBackground(new java.awt.Color(122, 71, 221));
        tbdata.setShowGrid(true);
        tbdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbdataMouseClicked(evt);
            }
        });
        tbdata.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbdataKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tbdata);
        if (tbdata.getColumnModel().getColumnCount() > 0) {
            tbdata.getColumnModel().getColumn(0).setPreferredWidth(10);
            tbdata.getColumnModel().getColumn(1).setPreferredWidth(10);
            tbdata.getColumnModel().getColumn(2).setPreferredWidth(10);
            tbdata.getColumnModel().getColumn(3).setPreferredWidth(10);
            tbdata.getColumnModel().getColumn(6).setMinWidth(0);
            tbdata.getColumnModel().getColumn(6).setMaxWidth(0);
        }

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tx_cari.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tx_cari.setToolTipText("");
        tx_cari.setActionCommand("<Not Set>");
        tx_cari.setBorder(null);
        tx_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_cariActionPerformed(evt);
            }
        });
        tx_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tx_cariKeyReleased(evt);
            }
        });
        jPanel3.add(tx_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 0, 320, 20));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 310, 10));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Pencarian");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 30));

        btn_dlt.setBackground(new java.awt.Color(255, 255, 255));
        btn_dlt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.magenta, java.awt.Color.blue, java.awt.Color.magenta, java.awt.Color.blue));
        btn_dlt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dltMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_dltMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_dltMouseExited(evt);
            }
        });

        tx_hapus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tx_hapus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tx_hapus.setText("Hapus");
        tx_hapus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout btn_dltLayout = new javax.swing.GroupLayout(btn_dlt);
        btn_dlt.setLayout(btn_dltLayout);
        btn_dltLayout.setHorizontalGroup(
            btn_dltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_dltLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(tx_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        btn_dltLayout.setVerticalGroup(
            btn_dltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tx_hapus, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        btn_view.setBackground(new java.awt.Color(255, 255, 255));
        btn_view.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.magenta, java.awt.Color.blue, java.awt.Color.magenta, java.awt.Color.blue));
        btn_view.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_viewMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_viewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_viewMouseExited(evt);
            }
        });

        tx_lihat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tx_lihat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tx_lihat.setText("Lihat");
        tx_lihat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout btn_viewLayout = new javax.swing.GroupLayout(btn_view);
        btn_view.setLayout(btn_viewLayout);
        btn_viewLayout.setHorizontalGroup(
            btn_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_viewLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(tx_lihat, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        btn_viewLayout.setVerticalGroup(
            btn_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tx_lihat, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel_inputLayout = new javax.swing.GroupLayout(panel_input);
        panel_input.setLayout(panel_inputLayout);
        panel_inputLayout.setHorizontalGroup(
            panel_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_inputLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panel_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panel_inputLayout.createSequentialGroup()
                            .addComponent(btn_view, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btn_dlt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        panel_inputLayout.setVerticalGroup(
            panel_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_inputLayout.createSequentialGroup()
                .addGroup(panel_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_inputLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_view, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_inputLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(btn_dlt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );

        panel_utama.add(panel_input, "card4");

        bg_awal.add(panel_utama, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 830, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg_awal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg_awal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bg_awal.getAccessibleContext().setAccessibleName("");

        setSize(new java.awt.Dimension(1131, 585));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_panFormMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_panFormMouseClicked
        // TODO add your handling code here
        panel_utama.removeAll();
        panel_utama.repaint();
        panel_utama.revalidate();
        
        panel_utama.add(panel_show);
        panel_utama.repaint();
        panel_utama.revalidate();
        
        String nam = "Data Mahasiswa";
        lbl_border.setText(nam);
        Clean();
    }//GEN-LAST:event_btn_panFormMouseClicked

    private void btn_panALLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_panALLMouseEntered
        // TODO add your handling code here:
        btn_panALL.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_btn_panALLMouseEntered

    private void btn_panALLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_panALLMouseExited
        // TODO add your handling code here:
        btn_panALL.setBackground(new Color(64,43,100));
    }//GEN-LAST:event_btn_panALLMouseExited

    private void btn_panAboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_panAboutMouseEntered
        // TODO add your handling code here:
        btn_panAbout.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_btn_panAboutMouseEntered

    private void btn_panAboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_panAboutMouseExited
        // TODO add your handling code here:
        btn_panAbout.setBackground(new Color(64,43,100));
    }//GEN-LAST:event_btn_panAboutMouseExited

    private void btn_panALLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_panALLMouseClicked
        // TODO add your handling code here:
        panel_utama.removeAll();
        panel_utama.repaint();
        panel_utama.revalidate();
        
        panel_utama.add(panel_input);
        panel_utama.repaint();
        panel_utama.revalidate();
        
        String nam = "Data Mahasiswa";
        lbl_border.setText(nam);
        Clean();
        
    }//GEN-LAST:event_btn_panALLMouseClicked

    private void btn_panAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_panAboutMouseClicked
        // TODO add your handling code here:
        panel_utama.removeAll();
        panel_utama.repaint();
        panel_utama.revalidate();
        
        panel_utama.add(panel_about);
        panel_utama.repaint();
        panel_utama.revalidate();
        
        String nam = "About Aplication .....";
        lbl_border.setText(nam);
        
    }//GEN-LAST:event_btn_panAboutMouseClicked

    private void btn_panFormMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_panFormMouseEntered
        // TODO add your handling code here:
        btn_panForm.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_btn_panFormMouseEntered

    private void btn_panFormMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_panFormMouseExited
        // TODO add your handling code here:
        btn_panForm.setBackground(new Color(64,43,100));
    }//GEN-LAST:event_btn_panFormMouseExited

    private void lbl_borderComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_lbl_borderComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_borderComponentShown

    private void tx_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_cariActionPerformed

    private void btn_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_exitMouseClicked

    private void btn_dltMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dltMouseClicked
        // TODO add your handling code here:
        int ok=JOptionPane.showConfirmDialog(null,"Apakah Yakin Mendelete record ini???", "Confirmation",JOptionPane.YES_NO_CANCEL_OPTION);
       if (ok==0){
        try{
            String sql="DELETE FROM tb_gdata1 WHERE nama='"+txt_nama.getText()+"'";
            java.sql.Connection conn=(java.sql.Connection)project.Koneksi.getConnection();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.executeUpdate();
            TampilData();
            JOptionPane.showMessageDialog(null, "Delete Data Sukses");
         }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, "Delete Data Gagal");
        }
       }
    }//GEN-LAST:event_btn_dltMouseClicked

    private void btn_viewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewMouseClicked
       
            // TODO add your handling code here:
            panel_utama.removeAll();
            panel_utama.repaint();
            panel_utama.revalidate();
            
            panel_utama.add(panel_show);
            panel_utama.repaint();
            panel_utama.revalidate();
            
            String nam = "Data Mahasiswa";
            lbl_border.setText(nam);
    }//GEN-LAST:event_btn_viewMouseClicked

    private void tbdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbdataMouseClicked
        // TODO add your handling code here:
        int baris = tbdata.rowAtPoint(evt.getPoint());
            String nim = tbdata.getValueAt(baris, 0).toString();
            txt_nim.setText(nim);
            String nama = tbdata.getValueAt(baris, 1).toString();
            txt_nama.setText(nama);
            String kelas = tbdata.getValueAt(baris, 2).toString();
            txt_kelas.setText(kelas);
            String dosen_pembimbing = tbdata.getValueAt(baris, 3).toString();
            txt_dosenpembimbing.setText(dosen_pembimbing);
            String tempat_tanggal = tbdata.getValueAt(baris, 4).toString();
            txt_tempat_tanggal.setText(tempat_tanggal);
            String agama = tbdata.getValueAt(baris, 5).toString();
            box_agama.setSelectedItem(agama);
            String jenis_kelamin = tbdata.getValueAt(baris, 6).toString();
            box_jeniskelamin.setSelectedItem(jenis_kelamin);
            String alamat = tbdata.getValueAt(baris, 7).toString();
            txt_alamat.setText(alamat);
            String notelp = tbdata.getValueAt(baris, 8).toString();
            txt_notelp.setText(notelp);
            String foto = tbdata.getValueAt(baris, 9).toString();
            lbl_photo.setText(foto);
    }//GEN-LAST:event_tbdataMouseClicked

    private void btn_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseEntered
        // TODO add your handling code here:
        btn_exit.setBackground(new Color(85,65,118));
        tx_exit.setForeground(Color.white);
    }//GEN-LAST:event_btn_exitMouseEntered

    private void btn_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseExited
        // TODO add your handling code here:
        btn_exit.setBackground(new Color(255,255,255));
        tx_exit.setForeground(Color.black);
    }//GEN-LAST:event_btn_exitMouseExited

    private void btn_viewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewMouseEntered
        // TODO add your handling code here:
        btn_view.setBackground(new Color(126,79,196));
        tx_lihat.setForeground(Color.white);
    }//GEN-LAST:event_btn_viewMouseEntered

    private void btn_viewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewMouseExited
        // TODO add your handling code here:
        btn_view.setBackground(new Color(255,255,255));
        tx_lihat.setForeground(Color.black);
    }//GEN-LAST:event_btn_viewMouseExited

    private void btn_dltMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dltMouseEntered
        // TODO add your handling code here:
        btn_dlt.setBackground(new Color(126,79,196));
        tx_hapus.setForeground(Color.white);
    }//GEN-LAST:event_btn_dltMouseEntered

    private void btn_dltMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dltMouseExited
        // TODO add your handling code here:
        btn_dlt.setBackground(new Color(255,255,255));
        tx_hapus.setForeground(Color.black);
    }//GEN-LAST:event_btn_dltMouseExited

    private void tbdataKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbdataKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tbdataKeyReleased

    private void tx_cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tx_cariKeyReleased
        // TODO add your handling code here:
        String key= tx_cari.getText();
        System.out.println(key);  
        
        if(!"".equals(key)){
            cariData(key);
        }else{
            TampilData();
        }
    }//GEN-LAST:event_tx_cariKeyReleased

    private void txt_tempat_tanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tempat_tanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tempat_tanggalActionPerformed

    private void txt_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaActionPerformed

    private void txt_nimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nimActionPerformed
        // TODO add your handling code here:
        try{   
                    java.sql.Statement st = (java.sql.Statement)  Koneksi.getConnection().createStatement();
                    ResultSet rs = st.executeQuery("SELECT * FROM `tb_gdata1` WHERE `tb_gdata1`.`nim` = '"+txt_nim.getText()+"'");
        
                    while(rs.next()){
                        txt_nama.setText(rs.getString("nama"));
                        txt_kelas.setText(rs.getString("kelas"));
                        txt_dosenpembimbing.setText(rs.getString("dosen_pembimbing"));
                        txt_tempat_tanggal.setText(rs.getString("tempat_tanggal"));
                        txt_alamat.setText(rs.getString("alamat"));
                        txt_notelp.setText(rs.getString("notelp"));
                        lbl_photo.setText(rs.getString("foto"));
                        box_agama.setSelectedItem(rs.getString("agama"));
                        box_jeniskelamin.setSelectedItem(rs.getString("jenis_kelamin"));
                    }
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null,"GAGAL");
                }             
        
    }//GEN-LAST:event_txt_nimActionPerformed

    private void btn_submit2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_submit2MouseExited
        // TODO add your handling code here:
        btn_submit2.setBackground(new Color(255,255,255));
        tx_perbarui.setForeground(Color.black);
    }//GEN-LAST:event_btn_submit2MouseExited

    private void btn_submit2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_submit2MouseEntered
        // TODO add your handling code here:
        btn_submit2.setBackground(new Color(126,79,196));
        tx_perbarui.setForeground(Color.white);
    }//GEN-LAST:event_btn_submit2MouseEntered

    private void btn_submit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_submit2MouseClicked
        // TODO add your handling code here:

        try{
            String sql = "UPDATE tb_gdata1 SET nim='" + txt_nim.getText() + "', nama= '" + txt_nama.getText() + "', kelas= '" + txt_kelas.getText()
            + "', dosen_pembimbing= '" + txt_dosenpembimbing.getText()+ "', tempat_tanggal= '" + txt_tempat_tanggal.getText()+ "', agama= '" + box_agama.getSelectedItem()+"', jenis_kelamin= '" + box_jeniskelamin.getSelectedItem() + "', alamat= '" + txt_alamat.getText() + "', notelp= '" + txt_notelp.getText() + "', foto= '" + lbl_photo.getText() + "' WHERE nim='" + txt_nim.getText() + "'" ;
            java.sql.Connection conn=(java.sql.Connection)project.Koneksi.getConnection();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Berhasil disimpan");
            TampilData();
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Gagal disimpan");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btn_submit2MouseClicked

    private void txt_dosenpembimbingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dosenpembimbingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dosenpembimbingActionPerformed

    private void txt_kelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kelasActionPerformed

    private void btn_submitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_submitMouseExited
        // TODO add your handling code here:
        btn_submit.setBackground(new Color(255,255,255));
        tx_simpan.setForeground(Color.black);
    }//GEN-LAST:event_btn_submitMouseExited

    private void btn_submitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_submitMouseEntered
        // TODO add your handling code here:
        btn_submit.setBackground(new Color(126,79,196));
        tx_simpan.setForeground(Color.white);
    }//GEN-LAST:event_btn_submitMouseEntered

    private void btn_submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_submitMouseClicked
        // TODO add your handling code here:
         try{
            String newpath = "src/uploud";
            File directory = new File(newpath);
            if(!directory.exists()){
                directory.mkdirs();
            }
            File fileawal = null;
            File fileakhir = null;
            String ext = this.filename.substring(filename.lastIndexOf('.')+1);
            fileawal = new File(filename);
            fileakhir = new File(newpath+"/"+txt_nim.getText()+"."+ext);
            System.out.print(fileakhir);
            Project1 a = new Project1();
            
            String sql = "INSERT INTO tb_gdata1(nim, nama, kelas, dosen_pembimbing, tempat_tanggal, agama, jenis_kelamin, alamat, notelp, foto) VALUES ('" + txt_nim.getText() + "','" + txt_nama.getText() + "','" + txt_kelas.getText() + "','"
            + txt_dosenpembimbing.getText() + "','" + txt_tempat_tanggal.getText() + "','" + box_agama.getSelectedItem() + "','" + box_jeniskelamin.getSelectedItem() + "','" + txt_alamat.getText() + "','" + txt_notelp.getText() + "','" + lbl_photo.getText() + "')";
            java.sql.Connection conn=(java.sql.Connection)project.Koneksi.getConnection();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            
            JOptionPane.showMessageDialog(null, "Data anda berhasil disimpan");
            Files.copy(fileawal.toPath(), fileakhir.toPath());
            TampilData();
            Clean();
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, "Gagal disimpan");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btn_submitMouseClicked

    private void box_agamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_agamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box_agamaActionPerformed

    private void txt_notelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_notelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_notelpActionPerformed

    private void txt_alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_alamatActionPerformed

    private void box_jeniskelaminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_jeniskelaminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box_jeniskelaminActionPerformed

    private void tx_simpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tx_simpanMouseClicked
        
         try{
            String newpath = "src/uploud";
            File directory = new File(newpath);
            if(!directory.exists()){
                directory.mkdirs();
            }
            File fileawal = null;
            File fileakhir = null;
            String ext = this.filename.substring(filename.lastIndexOf('.')+1);
            fileawal = new File(filename);
            fileakhir = new File(newpath+"/"+txt_nim.getText()+"."+ext);
            System.out.print(fileakhir);
            
            String sql = "INSERT INTO tb_gdata1(nim, nama, kelas, dosen_pembimbing, tempat_tanggal, agama, jenis_kelamin, alamat, notelp, foto) VALUES ('" + txt_nim.getText() + "','" + txt_nama.getText() + "','" + txt_kelas.getText() + "','"
            + txt_dosenpembimbing.getText() + "','" + txt_tempat_tanggal.getText() + "','" + box_agama.getSelectedItem() + "','" + box_jeniskelamin.getSelectedItem() + "','" + txt_alamat.getText() + "','" + txt_notelp.getText() + "','" + lbl_photo.getText() + "')";
            java.sql.Connection conn=(java.sql.Connection)project.Koneksi.getConnection();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            
            JOptionPane.showMessageDialog(null, "Data anda berhasil disimpan");
            Files.copy(fileawal.toPath(), fileakhir.toPath());
            TampilData();
            Clean();
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, "Gagal disimpan");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_tx_simpanMouseClicked

    private void btn_fotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fotoActionPerformed
       
           try {
        JFileChooser chooser =new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String path = f.getAbsolutePath();
            BufferedImage bi = ImageIO.read(new File(path));
            Image img =bi.getScaledInstance(152, 203, Image.SCALE_SMOOTH);
            ImageIcon ii = new ImageIcon(img);
            lbl_photo.setIcon(ii);
            this.filename = f.getAbsolutePath();
        }catch (Exception e){
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
    }//GEN-LAST:event_btn_fotoActionPerformed

    private void btn_fotoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btn_fotoStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_fotoStateChanged

    private void lbl_photoComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_lbl_photoComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_photoComponentAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Project1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Project1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Project1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Project1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Project1().setVisible(true);
                
            }
             
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg_awal;
    private javax.swing.JComboBox<String> box_agama;
    private javax.swing.JComboBox<String> box_jeniskelamin;
    private javax.swing.JPanel btn_dlt;
    private javax.swing.JPanel btn_exit;
    private javax.swing.JButton btn_foto;
    private javax.swing.JPanel btn_panALL;
    private javax.swing.JPanel btn_panAbout;
    private javax.swing.JPanel btn_panForm;
    private javax.swing.JPanel btn_submit;
    private javax.swing.JPanel btn_submit2;
    private javax.swing.JPanel btn_view;
    private javax.swing.JLabel ic_exit;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.ButtonGroup jb;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel label_user;
    private javax.swing.JLabel lbl_border;
    private javax.swing.JLabel lbl_photo;
    private javax.swing.JPanel panel_about;
    private keeptoo.KGradientPanel panel_border;
    private javax.swing.JPanel panel_input;
    private javax.swing.JPanel panel_show;
    private javax.swing.JPanel panel_utama;
    private javax.swing.JTable tbdata;
    private javax.swing.JTextField tx_cari;
    private javax.swing.JLabel tx_exit;
    private javax.swing.JLabel tx_hapus;
    private javax.swing.JLabel tx_lihat;
    private javax.swing.JLabel tx_perbarui;
    private javax.swing.JLabel tx_simpan;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_dosenpembimbing;
    private javax.swing.JTextField txt_kelas;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_nim;
    private javax.swing.JTextField txt_notelp;
    private javax.swing.JTextField txt_tempat_tanggal;
    // End of variables declaration//GEN-END:variables
}